// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/audit_checks": {
            "get": {
                "description": "Lists audit checks for a given ` + "`" + `search_keyword_url_id` + "`" + `",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AuditChecks"
                ],
                "summary": "List audit checks",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Search keyword URL ID",
                        "name": "search_keyword_url_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/audits.AuditChecksResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new audit check for a given ` + "`" + `search_keyword_url_id` + "`" + `",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AuditChecks"
                ],
                "summary": "Create audit check",
                "parameters": [
                    {
                        "description": "Audit check payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/audits.CreateAuditCheckRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/audits.AuditCheckResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/audit_checks/{id}": {
            "get": {
                "description": "Fetches an audit check by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AuditChecks"
                ],
                "summary": "Get audit check",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Audit check ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/audits.AuditCheckResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Updates an audit check by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AuditChecks"
                ],
                "summary": "Update audit check",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Audit check ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Audit check update payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/audits.UpdateAuditCheckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/audits.AuditCheckResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an audit check by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AuditChecks"
                ],
                "summary": "Delete audit check",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Audit check ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/audits.DeleteAuditCheckResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/crawling_sessions": {
            "post": {
                "description": "Creates a new crawling session for a SKU",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CrawlingSessions"
                ],
                "summary": "Create crawling session",
                "parameters": [
                    {
                        "description": "Crawling session payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sessions.CreateCrawlingSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/sessions.CrawlingSessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/crawling_sessions/{id}": {
            "get": {
                "description": "Fetches a crawling session by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CrawlingSessions"
                ],
                "summary": "Get crawling session",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Crawling session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sessions.CrawlingSessionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/crawling_sessions/{id}/checks_with_pages": {
            "get": {
                "description": "Lists audit checks with their associated pages for a session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CrawlingSessions"
                ],
                "summary": "List checks with pages",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Crawling session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Comparison session ID",
                        "name": "comparison_crawling_session_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "View filters JSON",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page limit per check",
                        "name": "page_limit_per_check",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sessions.CrawlingSessionChecksResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/crawling_sessions/{id}/pages": {
            "get": {
                "description": "Lists pages for a crawling session with optional filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CrawlingSessions"
                ],
                "summary": "List pages for crawling session",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Crawling session ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "JSON encoded filters",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort direction",
                        "name": "direction",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/sessions.CrawlingSessionPagesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/pages/{id}/page_details": {
            "get": {
                "description": "Returns images/referrers for a page depending on its status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pages"
                ],
                "summary": "Get page details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Search keyword URL ID",
                        "name": "search_keyword_url_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Result limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/stats.PageDetailsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/stats": {
            "get": {
                "description": "Retrieves stats for a crawling session with optional filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stats"
                ],
                "summary": "Fetch stats",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Crawling session ID",
                        "name": "crawling_session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "JSON filters",
                        "name": "filters",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "JSON prefilters",
                        "name": "prefilters",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Comparison session ID",
                        "name": "comparison_crawling_session_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/stats.StatsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/views": {
            "get": {
                "description": "Lists views for a given ` + "`" + `search_keyword_url_id` + "`" + `",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Views"
                ],
                "summary": "List views",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Search keyword URL ID",
                        "name": "search_keyword_url_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/views.ViewsResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new view",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Views"
                ],
                "summary": "Create view",
                "parameters": [
                    {
                        "description": "View payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/views.CreateViewRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/views.ViewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/views/{id}": {
            "get": {
                "description": "Fetches a view by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Views"
                ],
                "summary": "Get view",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "View ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/views.ViewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Updates a view by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Views"
                ],
                "summary": "Update view",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "View ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "View update payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/views.UpdateViewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/views.ViewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a view by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Views"
                ],
                "summary": "Delete view",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "View ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/views.DeleteViewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/views/{id}/page_count": {
            "get": {
                "description": "Returns a count of pages for the given view and optional crawling session filter",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Views"
                ],
                "summary": "View page count",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "View ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "View ID (must match path)",
                        "name": "view_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Crawling session ID",
                        "name": "crawling_session_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/views.ViewPageCountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns service health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.HealthResponse"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Exposes Prometheus metrics",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Prometheus metrics",
                "responses": {
                    "200": {
                        "description": "Metrics in Prometheus text format",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "audits.AuditCheckResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.AuditCheck"
                }
            }
        },
        "audits.AuditChecksResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AuditCheck"
                    }
                }
            }
        },
        "audits.CreateAuditCheckData": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "filter_config": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "name": {
                    "type": "string"
                },
                "search_keyword_url_id": {
                    "type": "integer"
                }
            }
        },
        "audits.CreateAuditCheckRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/audits.CreateAuditCheckData"
                }
            }
        },
        "audits.DeleteAuditCheckData": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "audits.DeleteAuditCheckResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/audits.DeleteAuditCheckData"
                }
            }
        },
        "audits.UpdateAuditCheckData": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "filter_config": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "audits.UpdateAuditCheckRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/audits.UpdateAuditCheckData"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "dto.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "models.AuditCheck": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "filterConfig": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "searchKeywordURLID": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.CheckWithPages": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "pages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Page"
                    }
                }
            }
        },
        "models.CrawlingSession": {
            "type": "object",
            "properties": {
                "aliases": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "dnsservers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "endReason": {
                    "type": "string"
                },
                "endedAt": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "externalResourcesCount": {
                    "type": "integer"
                },
                "externalURLsCount": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "ignoredURLsCount": {
                    "type": "integer"
                },
                "internalResourcesCount": {
                    "type": "integer"
                },
                "internalURLsCount": {
                    "type": "integer"
                },
                "ips": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "location": {
                    "type": "string"
                },
                "options": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "pagesCount": {
                    "type": "integer"
                },
                "queue": {
                    "type": "integer"
                },
                "robots": {
                    "type": "boolean"
                },
                "searchKeywordURLID": {
                    "type": "integer"
                },
                "sitemap": {
                    "type": "boolean"
                },
                "sslvalid": {
                    "type": "boolean"
                },
                "sslvalidUntil": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "models.Page": {
            "type": "object",
            "properties": {
                "crawling_session_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "response_code": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.PageImage": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "page_id": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.View": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "filterConfig": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "searchKeywordURLID": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "sessions.CrawlingSessionChecksData": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CheckWithPages"
                    }
                }
            }
        },
        "sessions.CrawlingSessionChecksResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/sessions.CrawlingSessionChecksData"
                }
            }
        },
        "sessions.CrawlingSessionPagesData": {
            "type": "object",
            "properties": {
                "pages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Page"
                    }
                },
                "pages_total": {
                    "type": "integer"
                }
            }
        },
        "sessions.CrawlingSessionPagesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/sessions.CrawlingSessionPagesData"
                }
            }
        },
        "sessions.CrawlingSessionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.CrawlingSession"
                }
            }
        },
        "sessions.CreateCrawlingSessionData": {
            "type": "object",
            "properties": {
                "options": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "queue": {
                    "type": "integer"
                },
                "search_keyword_url_id": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "sessions.CreateCrawlingSessionRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/sessions.CreateCrawlingSessionData"
                }
            }
        },
        "stats.PageDetailsData": {
            "type": "object",
            "properties": {
                "broken_pages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Page"
                    }
                },
                "page_images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PageImage"
                    }
                },
                "pages_linked_to_broken_page": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Page"
                    }
                }
            }
        },
        "stats.PageDetailsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/stats.PageDetailsData"
                }
            }
        },
        "stats.StatsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "views.CreateViewData": {
            "type": "object",
            "properties": {
                "filter_config": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "name": {
                    "type": "string"
                },
                "search_keyword_url_id": {
                    "type": "integer"
                }
            }
        },
        "views.CreateViewRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/views.CreateViewData"
                }
            }
        },
        "views.DeleteViewData": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "views.DeleteViewResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/views.DeleteViewData"
                }
            }
        },
        "views.UpdateViewData": {
            "type": "object",
            "properties": {
                "filter_config": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "views.UpdateViewRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/views.UpdateViewData"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "views.ViewPageCountData": {
            "type": "object",
            "properties": {
                "page_count": {
                    "type": "integer"
                }
            }
        },
        "views.ViewPageCountResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/views.ViewPageCountData"
                }
            }
        },
        "views.ViewResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.View"
                }
            }
        },
        "views.ViewsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.View"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Access token for authentication",
            "type": "apiKey",
            "name": "X-Access-Token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "SiteCrawler API",
	Description:      "Access token for authentication",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
